### PR TITLE
Config Option and Mayor Refactor 2.0.0.beta

### PR DESCRIPTION
**Pull request by vgarro**
Sidekiq::Enqueuer 2.0.0.beta is here with a mayor refactor and few features

[Features]
- [x] Config option to list jobs to be displayed (All jobs by default)
- [x] Sort Jobs by name ascending
- [x] Keep support for ActiveJob
- [ ] Keeps support for unlock!

[Refactor]
- [x] Refactor classes into their own sub-modules to provide Aotmic behavior
- [x] Worker module: Enqueing, Executing and Dynamic param lookup
- [x] WebExtension module: Sidekiq::WebExtension helpers, configuration and UI Param Parsing
- [x] Configuration module: Main Gem Configuration options
- [x] Unit test

### CODE REVIEW

**Comment by vgarro** [comment]
# Do not merge (not passing tests)

**Comment by vgarro** [comment]
@richfisher please review

**Comment by richfisher** [comment]
Awesome! :+1:

we can drop the support for unlock

**Comment by vgarro** [comment]
thanks for merging @richfisher

**Pull request merged**
